FIx Lang locale incoherence
wp-blocks/cf7-antispam pull request #77
Opened 2023-12-15 22:40 UTC by gardenboi

![image](https://github.com/wp-blocks/cf7-antispam/assets/118072927/430c7306-1163-4e75-a042-f212bdd29a58)

### The above representation is a summary of the code implementation.

Closes #44

**In this commit the following has been updated:**
- Assignations in Filters class (the logic is almost the same)
- added and modified Filters functions
- updated the Filter Tests accordingly
- updated the description in the admin settings

Now the language and locale are treated as separate entities, which are present on separate associative(key/value) arrays under the refactored option `language` now called
`languages_locales` ===> `allowed / disallowed` ===> `languages / locales` 

Now the end user can do the following:
- write languages as lower case 2 pair letters [ISO 639-1](https://www.loc.gov/standards/iso639-2/php/code_list.php)
- write languages as upper case 2 pair letters [ISO 3166-2](https://www.iso.org/obp/ui/#search)
- write language and locales together ex: `it-IT`

this means the settings field in the admin can be like the following:
**EX1**
```
it-IT
```
### EX2
```
it
IT
```
And still lead to the same behaviour

This PR will probably need some fixes, let me know @erikyo for further corrections.
Also I'd like to know @johnhooks if the explanations are clear or require better explanations.

2023-12-17 11:28 UTC, erikyo requested changes

2023-12-17 11:28 UTC, erikyo commented on engine/CF7_AntiSpam_Updater.php
> +*
?

2023-12-17 12:59 UTC, johnhooks commented on core/CF7_AntiSpam_Filters.php
> +					$language_disallowed = $this->cf7a_check_languages_locales_allowed( $client_languages, $languages_disallowed, $languages_allowed );
Is this checking the "sender has a blacklisted ip address?", it doesn't read that way.

2023-12-17 13:10 UTC, johnhooks reviewed
@gardenboi I left a few comments. Though I'm not familiar with the code being changed, I'll defer to @erikyo for approval. My general suggestions:

- If formatting changes need to happen in PRs, it's nice to do them before in a separate PR beforehand, having it mix with logical changes make it harder to review.
- I suggest breaking some of the larger functions into smaller ones, makes it easier to understand in code review and also when coming back to it later.

2023-12-17 19:38 UTC, gardenboi commented on core/CF7_AntiSpam_Filters.php
> +	}
yup, I just made an external function, not many PHPers are used to functional approach

2023-12-17 22:48 UTC, erikyo commented on core/CF7_AntiSpam_Filters.php
> +		);
```suggestion
	$languages = [];
	foreach ( $option as $item ) {
		$carry = is_array( $carry ) ? $carry : array();
		if ( $key == 'languages' ) {
			$l = $this->cf7a_check_length_exclusive( $item, 0 );
		} elseif ( $key == 'locales' ) {
			$l = $this->cf7a_check_length_exclusive( $item, 1 );
		}
		if ( ! empty( $l ) ) {
			$languages[] = $l;
		}
	}
	return array_values( array_unique( $languages ) );
```

2023-12-17 22:50 UTC, erikyo commented on core/CF7_AntiSpam_Filters.php
> +		);
In this way seems safer and less overcomplicated!

2023-12-17 22:53 UTC, erikyo commented on core/CF7_AntiSpam_Filters.php
> +	public function cf7a_check_length_exclusive( $el, $n ) {
```suggestion
	/**
	 * Checks the length of a string and returns a specific part of it based on a given index.
	 *
	 * @param string $el The input string to be checked.
	 * @param int $n The index used to retrieve a specific part of the string.
	 * @return string The extracted part of the string based on the given index, or an empty string if the conditions are not met.
	 */
	public function cf7a_check_length_exclusive( $el, $n ) {
```
	 please add a comment for each function. in this case should be fine

2023-12-17 23:09 UTC, erikyo commented on core/functions.php
> +function cf7a_get_accept_locales_array( $locales ) {
```suggestion
/**
 * Generates an array of accepted locales based on the given input.
 *
 * @param string $locales A comma-separated list of locales.
 * @return array An array of accepted locales.
 */
function cf7a_get_accept_locales_array( $locales ) {
```

2023-12-17 23:16 UTC, erikyo commented on core/functions.php
> +function cf7a_get_accept_locales_array( $locales ) {
is this an unused function? I cannot find where it was used anywere 🧐

2023-12-17 23:24 UTC, erikyo commented on cf7-antispam.php
> +	if ( $options && ! empty( $options['cf7a_enable'] ) ) {
I was wondering if it wouldn't be better to use !empty($options) instead of $options... although get_option can return false|mixed so, even if there are no options at all, it wouldn't be a real issue

2024-01-02 20:39 UTC, erikyo approved these changes

2024-01-02 23:11 UTC, merged